name: teachai_app
description: 毕节教师教育助手应用，支持离线使用的AI教育工具
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_markdown: ^0.6.18
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_gemma: ^0.0.4
  dio: ^5.4.0

  # Tour引导功能
  showcaseview: ^3.0.0
  
  # 登录和认证
  crypto: ^3.0.3
  
  # 动画效果
  lottie: ^3.1.0
  
  # Loading覆盖层
  loader_overlay: ^5.0.0
  
  # Loading动画组件
  loading_animation_widget: ^1.3.0

  # 仅在移动平台使用的依赖，Web会按条件导入
  google_mlkit_text_recognition: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
